{% set name = "sankee" %}
{% set version = "0.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sankee-{{ version }}.tar.gz
  sha256: ce04442f1ec1aa1f0cca2dab794ca0fbfecece44af681b902a94d96c84993869

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - earthengine-api >=0.1.230
    - ipykernel
    - nbformat >=4.2.0
    - numpy
    - pandas
    - plotly
    - python >=3.6

test:
  imports:
    - sankee

about:
  home: https://github.com/aazuspan/sankee
  summary: Visualize classified time series data with interactive Sankey plots in Google Earth Engine.
  dev_url: https://github.com/aazuspan/sankee/
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aazuspan
