{% set name = "sankee" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sankee-{{ version }}.tar.gz
  sha256: 1871de48464c4f4fc2de11a2afa0d4d82c93d57da8ada05cd3bbcde96dda4240

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - earthengine-api >=0.1.230
    - numpy
    - pandas
    - plotly >=5.2.2
    - python >=3.6

test:
  imports:
    - sankee

about:
  home: https://github.com/aazuspan/sankee
  summary: Visualize classified time series data with interactive Sankey plots in Google Earth Engine.
  dev_url: https://github.com/aazuspan/sankee/
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aazuspan
